name: CI for Steam API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install dependencies
      run: |
        Rscript -e "install.packages('httr2')"
        Rscript -e "install.packages('jsonlite')"

    - name: Install devtools
      run: |
        Rscript -e "install.packages('devtools', repos = 'https://cloud.r-project.org/')"

    - name: Install local package
      run: |
        Rscript -e "devtools::install('.')"

    - name: Run the R API
      run: |
        nohup Rscript R/steamR.R &
        sleep 5

    - name: Run tests
      run: |
        Rscript tests/test_all.R
